version: '2'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    # image: biarms/mysql:5.7.30-linux-arm64v8 for raspberry pi
    environment:
      MYSQL_DATABASE: manage_vinyl_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/workdir
    restart: unless-stopped